// generated by stringer -type=FlagState,UserType -output=types_strings.go; DO NOT EDIT

package twitch

import "fmt"

const _FlagState_name = "EnabledDisabledUndefined"

var _FlagState_index = [...]uint8{0, 7, 15, 24}

func (i FlagState) String() string {
	if i < 0 || i >= FlagState(len(_FlagState_index)-1) {
		return fmt.Sprintf("FlagState(%d)", i)
	}
	return _FlagState_name[_FlagState_index[i]:_FlagState_index[i+1]]
}

const _UserType_name = "PlebsModeratorGlobalModeratorTwitchStaffTwitchAdmin"

var _UserType_index = [...]uint8{0, 5, 14, 29, 40, 51}

func (i UserType) String() string {
	if i < 0 || i >= UserType(len(_UserType_index)-1) {
		return fmt.Sprintf("UserType(%d)", i)
	}
	return _UserType_name[_UserType_index[i]:_UserType_index[i+1]]
}
