# this configuration is used for the tests

account:
  username: bot
  password: foobar
operator: op
database:
  DSN: 'develop:develop@/kabukibot_test'
commandPrefix: k_
plugins:
  speedruncom:
    mapping:
      Grand_Theft_Auto_London_1961:
        zjdzpgkv: { dict: gta_wr_london61_any, commands: [wr_test] }

irc:
  host: irc.twitch.tv
  port: 6667
